# Load default processing options
imports:
- { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
- { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
- { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

# Add configuration for the editor
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config
editor:
  config:
    contentsCss: "EXT:schmidtwebmedia/Resources/Public/css/ckeditor.min.css"
    stylesSet:
    - { name: "Button Primary", element: "a", attributes: { class: "button button-primary"} }
    - { name: "Button Secondary", element: "a", attributes: { class: "button button-secondary"} }
    - { name: "Small Text", element: "span", attributes: { class: "small-text"} }
    - { name: "Smaller Text", element: "span", attributes: { class: "smaller-text"} }
    - { name: "Big Text", element: "span", attributes: { class: "big-text"} }
    - { name: "Bigger Text", element: "span", attributes: { class: "bigger-text"} }
    - { name: "Light Text", element: "span", attributes: { class: "light-text"} }
    - { name: "Footer Table", element: "table", attributes: { class: "table-footer" } }


    format_tags: "p;h1;h2;h3;h4;h5;address"

    toolbarGroups:
    - { name: styles, groups: [ styles, format ] }
    - { name: basicstyles, groups: [ basicstyles ] }
    - { name: paragraph, groups: [ list, indent, blocks, align ] }
    - { name: links, groups: [ links ] }
    - { name: clipboard, groups: [ clipboard, cleanup, undo ] }
    - { name: editing, groups: [ spellchecker ] }
    - { name: insert, groups: [ insert ] }
    - { name: tools, groups: [ table, specialchar ] }
    - { name: document, groups: [ mode ] }

    justifyClasses:
    - text-left
    - text-center
    - text-right
    - text-justify

    extraPlugins:
    - justify

    removePlugins:
    - image

    removeButtons:
    - Strike
    - Anchor
    - Outdent
    - Indent
    - Blockquote
    - JustifyBlock

    defaultContentLanguage: "de"
    defaultLanguage: "de"
    contentsLanguage: "de"
    language: "de"
    scayt_autoStartup: true # Spellcheck always on
    scayt_sLang: "de_DE" # spellcheck language
    wsc_lang: "de_DE"
